# Generated by Django 4.0.4 on 2022-06-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('voltage', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer'],
            },
        ),
    ]
