# Generated by Django 4.0.4 on 2022-06-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cnpj_alter_client_cpf_alter_client_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_ddd',
            field=models.CharField(blank=True, default='11', max_length=3, null=True),
        ),
    ]
