# Generated by Django 4.0.4 on 2022-05-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('voltage', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('imported', models.BooleanField(default=0)),
                ('assurance', models.DateTimeField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.manufacturer')),
            ],
        ),
    ]
