# Generated by Django 4.0.4 on 2022-06-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentform',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'ordering': ['id']},
        ),
    ]
